/**
 * Rank badge emojis.
 *
 * These are APPLICATION emojis, not guild emojis: a public bot can't rely on
 * any particular server having uploaded them, and application emojis render in
 * every server the app is in. Source art is generated by
 * `scripts/make-rank-badges.py` and uploaded once per application.
 *
 * Resolved by NAME at startup rather than hardcoded by id, because the live and
 * dev applications each hold their own copies with different ids. Hardcoding
 * either set would leave the other rendering raw `<:rank7:123>` text.
 *
 * Everything degrades to a plain text badge if the fetch fails or the emojis
 * were never uploaded, so a missing asset can never break a command.
 */
import type { Client } from "discord.js";
import { MAX_RANK } from "./battle.js";

const badges = new Map<number, string>();

/** Call once the client is ready. Failure is non-fatal by design. */
export async function loadRankBadges(client: Client): Promise<void> {
  try {
    const emojis = await client.application?.emojis.fetch();
    if (!emojis) return;
    for (const emoji of emojis.values()) {
      const match = /^rank(\d+)$/.exec(emoji.name ?? "");
      if (!match) continue;
      const rank = Number(match[1]);
      if (rank >= 1 && rank <= MAX_RANK) badges.set(rank, emoji.toString());
    }
    console.log(`loaded ${badges.size} rank badges`);
  } catch (err) {
    console.error("rank badges unavailable, falling back to text:", err);
  }
}

/**
 * Badge for a rank, or empty string for rank 1 and below.
 *
 * Rank 1 is deliberately unmarked: it is the default state of every card, so
 * badging it would put an emoji on every row of every collection and mean
 * nothing.
 */
export function rankBadge(rank: number): string {
  if (!rank || rank <= 1) return "";
  return badges.get(rank) ?? `\`R${rank}\``;
}

/** Badge plus a space, for prefixing a card name without a stray gap at rank 1. */
export function rankPrefix(rank: number): string {
  const badge = rankBadge(rank);
  return badge ? `${badge} ` : "";
}
